### ISSUE TITLE
不能获取nasa数据

### ISSUE THREAD

**Issue by hhdang** [chongchonghe/Python-solar-system#1]
翻了墙能上Google，没能拿到nasa数据，请问还有别的方法获取行星数据吗

requests.exceptions.ProxyError: HTTPSConnectionPool(host='ssd.jpl.nasa.gov', port=443): Max retries exceeded with url: /horizons_batch.cgi?batch=1&TABLE_TYPE=VECTORS&OUT_UNITS=AU-D&COMMAND=%221%22&CENTER=%27%40sun%27&CSV_FORMAT=%22YES%22&REF_PLANE=ECLIPTIC&REF_SYSTEM=J2000&TP_TYPE=ABSOLUTE&LABELS=YES&VECT_CORR=%22NONE%22&VEC_DELTA_T=NO&OBJ_DATA=YES&TLIST=2458119.5 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1059: The handshake operation timed out')))

**Comment by chongchonghe** [comment]
NASA的API应该是公开的，所有地方都可以用。国内也没有理由墙掉这个。可能是因为延时的原因导致超时。可以试一试用VPN或者 shadowsocks。

对于这个小程序，实时获取行星数据是没有必要的，因为我们只需要一个初始条件。所以我更新了 solar_system.py 使得它从 planets.json 获取数据，所以现在不需要调用 NASA 的 API 了。planets.json 是通过 get_planet_pos.py 调取 NASA 数据活的的。
