### ISSUE TITLE
无法获取数据

### ISSUE THREAD

**Issue by lanchaoxiang** [chongchonghe/Python-solar-system#2]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ssd.jpl.nasa.gov', port=443): Max retries exceeded with url: /horizons_batch.cgi?batch=1&TABLE_TYPE=VECTORS&OUT_UNITS=AU-D&COMMAND=%221%22&CENTER=%27%40sun%27&CSV_FORMAT=%22YES%22&REF_PLANE=ECLIPTIC&REF_SYSTEM=J2000&TP_TYPE=ABSOLUTE&LABELS=YES&VECT_CORR=%22NONE%22&VEC_DELTA_T=NO&OBJ_DATA=YES&TLIST=2459215.5 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000270754F4400>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

**Comment by chongchonghe** [comment]
Please refer to #1
