### ISSUE TITLE
Equation Question

### ISSUE THREAD

**Issue by Greg-Kojadinovich** [chongchonghe/Python-solar-system#3]
acc = -2.959e-4 * p.r / np.sum(p.r**2)**(3./2)  # in units of AU/day^2

where does this equation come from? I haven't been able to find it. 

awesome project! thanks for sharing. 

this is the only reference I have been able to find related to the constant. 

https://www.mathworks.com/matlabcentral/answers/491933-two-body-problem-using-ode45

**Comment by chongchonghe** [comment]
According to Newton's law, the acceleration of a planet is a = G Msun / r^2, which is proportional to 1/r^2, in the direction opposite of the r vector. Mathematically, this is represented with - r / |r|^3, where r is the vector r. That is where `p.r / np.sum(p.r**2)**(3./2)` comes from. Note that `np.sum(p.r**2)` equals |r|^2. The `-2.959e-4` in the front is the proportionality constant in units of AU/day^2 which comes from the fact that `G Msun / AU^2 = 0.0002959 AU/day^2`.

**Comment by Greg-Kojadinovich** [comment]
Thank you for the explanation. This is very helpful. I still cannot figure out what I am missing to calculate the proportionality constant. I am new to these formulas and assuming this is not a rounding error.

<img width="464" alt="Screen Shot 2022-04-25 at 9 22 22 PM" src="https://user-images.githubusercontent.com/64438820/165200183-e18c2ca0-d2dc-445a-af0e-9252959554d4.png">

Here are the values I am getting.

**Comment by chongchonghe** [comment]
G M_sun / AU^2 = 0.005930083518 m / s2 = 0.0002959122082 AU / day^2
